# don't change!
version: 1

#----------Invites----------#
# Time in minutes until an invite expires. Can take longer depending on the server TPS!
invite-expires-after: 3

#----------General----------#
# Specifies whether the Minecraft teams should be used.(recommended) Changing this value while clans are already created can cause errors!
use-minecraft-teams: true
# Limits the clan name length. It is recommended not to set the length higher than 12, from 16 errors can occur!
max-clanname-lenght: 8

#---------Functions---------#
# Defines whether the clan base should be activated.
clan-base: true
# Sets the cooldown for /clans base in minutes. It is disabled at 0.
clan-base-cooldown: 5
